/**
 * All right is from Author of the file,to be explained in comming days.
 * Nov 14, 2012
 */
package com.fs.uicommons.impl.gwt.client.frwk.login;

import com.fs.uicommons.api.gwt.client.frwk.login.LoginModelI;
import com.fs.uicommons.api.gwt.client.mvc.ControlI;
import com.fs.uicommons.api.gwt.client.mvc.support.APSupport;
import com.fs.uicommons.api.gwt.client.mvc.support.ControlUtil;
import com.fs.uicore.api.gwt.client.UiRequest;
import com.fs.uicore.api.gwt.client.UiResponse;
import com.fs.uicore.api.gwt.client.data.ErrorInfosData;
import com.fs.uicore.api.gwt.client.data.basic.StringData;

/**
 * @author wu
 *         <p>
 *         Auto auth through data in client side.
 *         <p>
 *         this is called after got the session id.
 */
public class AnonymousAP extends APSupport {

	protected String reqType;

	protected static final String RT_RU = "SRU";// saved registered
	protected static final String RT_AU = "SAU";// saved anonymous
	protected static final String RT_NO = "SNO";// no user saved

	/*
	 * Nov 14, 2012
	 */
	@Override
	public void processRequest(ControlI c, String a, UiRequest req) {

	}

	@Override
	protected void processResponseWithError(final ControlI c, final String a,
			UiResponse res, ErrorInfosData eis) {
		super.processResponseWithError(c, a, res, eis);
	}

	/*
	 * Nov 14, 2012 Note: if client side not contains accountinfo, there will be
	 * 2 request: 1)first one will create a annonymous account/password;
	 * 2)second one will use this to auth again.
	 */
	@Override
	public void processResponseSuccess(ControlI c, String a, UiResponse res) {

		AccountsLDW sai = AccountsLDW.getInstance();
		// save to client and schedule to send again the auth action,see
		// processRequest of this.
		LoginModelI lm = (LoginModelI) c.getModel();
		StringData accId = (StringData) res.getPayload("accountId", true);//
		StringData password = (StringData) res.getPayload("password", true);
		// accountId and password generated by serverside,so saving it
		// before auth is ok.
		AnonymousAccountLDW aal = sai.getAnonymous();
		aal.save(accId.getValue(), password.getValue());// save anonymous
														// account.
		lm.setIsUsingSavedAccout(true);//
		ControlUtil.triggerAction(c.getModel(), LoginModelI.A_SUBMIT);//

	}
}
